spring.application.name=Ticket_BackEnd
# Postgre DB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Redis
spring.data.redis.host=${SPRING_EC2_URL}
spring.data.redis.port=6379
spring.data.redis.password=${SPRING_REDIS_PASSWORD}
spring.data.redis.timeout=6000
#logging.level.root=TRACE
# Mybatis
mybatis.mapper-locations=classpath:/mapper/**/*.xml
#type-aliases
mybatis.type-aliases-package=com.ssafy.ticket_backend.dto
# Automatically maps snake_case column names to camelCase Java properties
mybatis.configuration.map-underscore-to-camel-case=true
# JWT Secret Key
jwt.secret=${JWT_SECRET}
# KaKak OAuth REST API KEY
kakao.rest.api.key=${KAKAO_REST_API_KEY}
# Naver OAuth
naver.client.id=${NAVER_CLIENT_ID}
naver.client.secret=${NAVER_CLIENT_SECRET}
# KakaoPay
kakaopay.api-key=${KAKAOPAY_API_KEY}
kakaopay.cid=TC0ONETIME
kakaopay.host=https://kapi.kakao.com
kakaopay.ready-url=/v1/payment/ready
kakaopay.approve-url=open-api.kakaopay.com/payment/approve
kakaopay.success-url=/payment/kakao/success
# Aws S3
cloud.aws.credentials.access-key=${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
cloud.aws.s3.bucket=team-109-lions
cloud.aws.region.static=ap-northeast-2
cloud.aws.stack.auto=false
# URL
FE_BASE_URL=${FE_BASE_URL}
BE_BASE_URL=${BE_BASE_URL}
# FE_BASE_URL=http://localhost:5173
# BE_BASE_URL=http://localhost:8080
# SMS
SMS_API_KEY=${SMS_API_KEY}
SMS_API_SECRET_KEY=${SMS_API_SECRET_KEY}