spring.application.name=Ticket_BackEnd
# Postgre DB
spring.datasource.url=jdbc:postgresql://localhost:5432/goldenticket
spring.datasource.username=test
spring.datasource.password=test
spring.datasource.driver-class-name=org.postgresql.Driver