spring.application.name=Ticket_BackEnd
# Postgre DB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# Redis
spring.data.redis.host=${SPRING_EC2_URL}
spring.data.redis.port=6379
spring.data.redis.password=${SPRING_REDIS_PASSWORD}
spring.data.redis.timeout=6000
#logging.level.root=TRACE
# Mybatis
mybatis.mapper-locations=classpath:/mapper/**/*.xml
#type-aliases
mybatis.type-aliases-package=com.ssafy.ticket_backend.dto
# JWT Secret Key
jwt.secret=${JWT_SECRET}
# KaKak OAuth REST API KEY
kakao.rest.api.key=${KAKAO_REST_API_KEY}
# Naver OAuth
naver.client.id=${NAVER_CLIENT_ID}
naver.client.secret=${NAVER_CLIENT_SECRET}
# KakaoPay
kakaopay.api-key=aa416940de7494e47af4c4b029119a8a
kakaopay.cid=TC0ONETIME
kakaopay.host=https://kapi.kakao.com
kakaopay.base-url=http://localhost:8080
kakaopay.ready-url=/v1/payment/ready
kakaopay.approve-url=/payment/approve
kakaopay.success-url=/payment/success
kakaopay.cancel-url=/payment/cancel
kakaopay.fail-url=/payment/fail