stages:
  - build
  - deploy

variables:
  EC2_HOST: i13a109.p.ssafy.io
  PRIVATE_KEY: $SSH_PRIVATE_KEY  # GitLab에 등록 필요

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

build:
  stage: build
  image: node:11
  script:
    - npm install
    - npm run build  # dist/ 폴더 생성

deploy:
  stage: deploy
  image: node:11
  script:
    - scp -r dist/* $EC2_HOST:/var/www/html/  # 원하는 배포 경로
    - ssh $EC2_HOST "sudo systemctl restart nginx"
